version: '2'

services:
    front:
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - .:/usr/share/nginx/html
        working_dir: /usr/share/nginx/html
        ports:
            - 8081:80
        environment:
            - PORT=80
